version: '3.0'

services:
  main:
    container_name: server
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongodb
    restart: always

  mongodb:
    container_name: database
    image: mongo:5.0.0
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  mongodb-data:
